# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20170413_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('short_description', models.CharField(max_length=60)),
                ('long_description', models.TextField(max_length=2000)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Image')),
            ],
        ),
    ]
