# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20170413_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='shortname',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
