# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_person_shortname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='long_description',
            field=models.TextField(),
        ),
    ]
